name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Terraform state branch
        run: |
          git fetch origin state || git checkout --orphan state
          git checkout state
          mkdir -p tfstate
          git reset --hard
          git checkout main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::AKIA5ZDRXEUJX4XJID6N:role/g3-role
          aws-region: eu-west-3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Save Terraform state
        run: |
          git checkout state
          mv tfstate/terraform.tfstate .
          git add terraform.tfstate
          git commit -m "Update Terraform state (destroyed)"
          git push origin state